apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-master
  namespace: elastic-search-local
  labels:
    k8s-app: elasticsearch-master
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-master
  labels:
    k8s-app: elasticsearch-master
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: elastic-search-local
  name: elasticsearch-master
  labels:
    k8s-app: elasticsearch-master
subjects:
  - kind: ServiceAccount
    name: elasticsearch-master
    namespace: elastic-search-local
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch-master
  apiGroup: ""

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: elastic-search-local
  labels:
    k8s-app: elasticsearch-master
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: db
  selector:
    k8s-app: elasticsearch-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: elastic-search-local
  labels:
    k8s-app: elasticsearch-master
spec:
  serviceName: elasticsearch-master
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: elasticsearch-master
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-master
    spec:
      serviceAccountName: elasticsearch-master
      containers:
        - image: elasticsearch:6.8.4
          name: elasticsearch-master
          ports:
            - containerPort: 9200
              name: db
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: elasticsearch-master
              mountPath: /data
          env:
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: elasticsearch-master
          emptyDir: {}
      initContainers:
        - image: alpine:3.6
          command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
          name: elasticsearch-master-init
          securityContext:
            privileged: true
