apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ahb-dtp-test-framework
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: [ "obp-cit" ]
      to:
        - operation:
            methods: [ "GET", "POST", "PUT", "DELETE" ]
            paths:
              - "/*"
              - "/*"
